Package: gencpp
Version: 0.1.2
Section: misc
Priority: extra
Architecture: any
Depends: python-empy, @(PackagePrefix)genmsg, @(PackagePrefix)catkin
Build-Depends: python, python-empy, python-setuptools,
               @(PackagePrefix)catkin, @(PackagePrefix)genmsg 
Description: ros message generation, cpp style.
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Catkin-ProjectName: gencpp
Catkin-CopyrightType:  willowgarage
Catkin-Depends: catkin, genmsg
Catkin-ROS-Message-Generator: cpp
Catkin-DebRulesType: python_distutils

Release-Pull: git://github.com/wg-debs/gencpp.git
Release-Push: git@github.com:wg-debs/gencpp.git

