Package: gencpp
Version: 3.4.5
Section: misc
Priority: extra
Architecture: all
Depends: ${misc:Depends} python-empy, cmake, make, @(CATKIN_PACKAGE_PREFIX)genmsg, @(CATKIN_PACKAGE_PREFIX)catkin
Build-Depends: debhelper (>= 7), cmake, gcc, make, python, python-empy, python-setuptools,
               @(CATKIN_PACKAGE_PREFIX)catkin, @(CATKIN_PACKAGE_PREFIX)genmsg 
Description: Willow Garage low level build system macros and infrastructure
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Catkin-ProjectName: gencpp
Catkin-CopyrightType:  willowgarage
Catkin-Depends: catkin, genmsg
Catkin-ROS-Message-Generator: cpp
Catkin-DebRulesType: python_distutils
